### ISSUE TITLE
dataset availability

### ISSUE THREAD

**Issue by sdxass** [mks0601/3DMPPE_ROOTNET_RELEASE#1]
Hi,

Thank you for opening source such a great work! I would like to ask when will you release the pre-processed dataset or can you share the pre-processing code? Look forward to your response.

**Comment by mks0601** [comment]
Hi, you can download pre-processed dataset. Please refer to README

**Comment by sdxass** [comment]
It seems that the links you provided are not available.

**Comment by mks0601** [comment]
Oh sorry there were some mistakes at URLs. You can download now!

**Comment by sdxass** [comment]
Thank you for your help!
