### ISSUE TITLE
what is the difference between protocol1 and protocol2 bbox?

### ISSUE THREAD

**Issue by wangzheallen** [mks0601/3DMPPE_ROOTNET_RELEASE#10]
For H36M.

**Comment by mks0601** [comment]
As described in my paper, 
protocol 1 uses subject 1, 5, 6, 7, 8, 9 as training set, and subject 11 as testing set.
protocol 2 uses subject 1, 5, 6, 7, 8 as training set, and subject 9, 11 as testing set.

The bboxs are bbox prediction results on testing set. Therefore, bbox of protocol 2 includes bbox of protocol 1.

**Comment by wangzheallen** [comment]
Thanks! I was thinking mpjpe and pmpjpe, thanks for clarification!
