### ISSUE TITLE
Where is Human36M/bbox/bbox_human36m_output.json

### ISSUE THREAD

**Issue by ykamikawa** [mks0601/3DMPPE_ROOTNET_RELEASE#11]
Hi, Thank you for your great works!!

I would like to train this model from scrach.
Where can I get `bbox_human36m_output.json`?

**Comment by ykamikawa** [comment]
and, I would like to know the difference of `root_img` and `root_viz` .

**Comment by mks0601** [comment]
1. You can download at README.
2. `root_img` is coordinate, and `root_vis` is binary value which indicates root is visible or not.

**Comment by ykamikawa** [comment]
1. Thank you for your prompt response. 
2. Is `root_img` coordinate in the original image or the cropped image?

**Comment by mks0601** [comment]
Could you specify by the line number and code file name?
