### ISSUE TITLE
Dataset and visualization?

### ISSUE THREAD

**Issue by Yxiaoqian** [mks0601/3DMPPE_ROOTNET_RELEASE#14]
1.   how can I get the visualization results?  It's seems that there is no visualization code, I want to get the visualization results like your demonstration.

2. I don't understand the datasets's json files,  such as Human36M_subjectx.json， there are some information about camera parameters, but aren't the real coordination (x,y,z) about human? How can I know the real (x, y, z)? 

3. the test result 'bbox_root_human36m_output.json', there are information about 'bbox' and 'root_cam', no information prediction coordination (x, y, z)? How can I know the prediction (x, y, z)? 

Sorry to bother you,  thank you very much!

**Comment by mks0601** [comment]
I think you are interested in https://github.com/mks0601/3DMPPE_POSENET_RELEASE
This repo contains RootNet.

**Comment by Yxiaoqian** [comment]
woo, thank you very much !!!
