### ISSUE TITLE
UnboundLocalError: local variable 'bbox' referenced before assignment 

### ISSUE THREAD

**Issue by banana16314** [mks0601/3DMPPE_ROOTNET_RELEASE#15]
https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE/blob/4202715d7ef27f0ed3edca887ecaadc4e3fcf9c4/data/MPII/MPII.py#L37

Hey, man, there is a small mistake. bbox shall be ann['bbox'] 
as the POSENET _bbox = process_bbox(ann['bbox'], width, height)_

**Comment by mks0601** [comment]
I fixed it . Thanks!
