### ISSUE TITLE
How did you create the annotation file for Human3.6m dataset?

### ISSUE THREAD

**Issue by nile649** [mks0601/3DMPPE_ROOTNET_RELEASE#2]
I was wondering how did you find values of following variables, or was it already given in Human3.6 data set?
  **'cam_param': ,'t':, 'f':,'c':** and why there is assumption that real image area is 2kx2k?

**Comment by mks0601** [comment]
All the cam_params are already given in H36M datasets. For the real image assumption, please read section 5 of the paper.

**Comment by nile649** [comment]
Thanks, I did read the assumption still 2000x2000, Did you arrive on this number experimentally?

**Comment by mks0601** [comment]
No, I manually set that number. I extend bounding box about 1.2 times and make the aspect ratio 1:1. I thought this extended bounding box would be roughly 2m x 2m in real scale. Of course our RootNet refine it from image feature.
