### ISSUE TITLE
Cannot get reported AP on MuPoTS dataset

### ISSUE THREAD

**Issue by lhyfst** [mks0601/3DMPPE_ROOTNET_RELEASE#22]
I downloaded the bbox from https://drive.google.com/drive/folders/1y0NM6dBbfQgOTRQ6t-V6qdvIt2J6rndS and downloaded the pre-trained model from https://drive.google.com/drive/folders/1nQfOIgc7_AG5xPAO-vtG_L0WxdOelxet. But I could not reproduce the AP score(31.0) reported in README.md

My result is
```
~/3DMPPE_ROOTNET_RELEASE/main$ python test.py --gpu 1 --test_epoch 18
>>> Using GPU: 1
07-14 17:00:48 Creating dataset...
loading annotations into memory...
Done (t=1.49s)
creating index...
index created!
Get bounding box from ../data/MuPoTS/bbox/bbox_mupots_output.json
07-14 17:00:58 Load checkpoint from ../output/muco_coco/model_dump/snapshot_18.pth.tar
07-14 17:00:58 Creating graph...
100%|████████████████████████████████████| 2163/2163 [16:05<00:00,  2.24it/s]
Evaluation start...
Test result is saved at ../output/muco_coco/result/bbox_root_mupots_output.json
loading annotations into memory...
Done (t=1.74s)
creating index...
index created!
AP_root: 0.1514230417627361
```

**Comment by mks0601** [comment]
![image](https://user-images.githubusercontent.com/13601723/87495718-0a141c80-c68d-11ea-9b54-0586263d6f3f.png)

This is what I've got just before.
The bbox link you provided contains root joint coordinates and *extended bbox*.
You should use https://drive.google.com/drive/u/1/folders/1LVpqm6WoiaH0320kKDQDxXrHZs6xHnwt

**Comment by lhyfst** [comment]
Thanks for reply :)

However, the link you provide needs access

![67f1f30d13f37dd869eae20400b56e1](https://user-images.githubusercontent.com/29816816/87497574-5f99fa80-c688-11ea-8769-b2e25fb1e5eb.png)

**Comment by mks0601** [comment]
Sorry I forgot to share this in public.
You can use this [link](https://drive.google.com/drive/folders/1oBluPpX1YV5YLOU7qytbvdUkn0tp_Yyk?usp=sharing) or the link at README.

**Comment by lhyfst** [comment]
Thanks:)
