### ISSUE TITLE
data/PW3D

### ISSUE THREAD

**Issue by zqq-judy** [mks0601/3DMPPE_ROOTNET_RELEASE#26]
Hello！
I can't find this  "joint_cam". And it is not found in the 3DPW_train.json file.

`Traceback (most recent call last):`
`  File "train.py", line 83, in <module>`
    `main()`
 `File "train.py", line 33, in main`
    `trainer._make_batch_generator()`
  `File "/home/zqq/project/3DMPPE_ROOTNET_RELEASE-master/main/../common/base.py", line 94, in _make_batch_generator
    trainset3d_loader.append(DatasetLoader(eval(cfg.trainset_3d[i])("train"), True, transforms.Compose([\`
  `File "/home/zqq/project/3DMPPE_ROOTNET_RELEASE-master/main/../data/PW3D/PW3D.py", line 18, in __init__
    self.data = self.load_data()`
  `File "/home/zqq/project/3DMPPE_ROOTNET_RELEASE-master/main/../data/PW3D/PW3D.py", line 35, in load_data
    joint_cam = np.array(ann['joint_cam'], dtype=np.float32).reshape(-1,3)`
`KeyError: 'joint_cam'`

**Comment by mks0601** [comment]
Sorry I updated `.json` files. Now, it will work.

**Comment by zqq-judy** [comment]
Hi, I have another question.
In the xxx.py file of the loaded datasets, there is a line of code.
 For example, in MSCOCO.py, 
`joint_img = np.array(ann['keypoints']).reshape(-1,3)`
, what is the meaning of keypoints ? What is the purpose of this line of code?

**Comment by mks0601** [comment]
It is 2D joint coordinates of MSCOCO. See [here](https://cocodataset.org/#format-data)
