### ISSUE TITLE
The world coordinates of PW3D dataset

### ISSUE THREAD

**Issue by andgitchang** [mks0601/3DMPPE_ROOTNET_RELEASE#28]
I would like to ask if it's available to get the world coordinates of the joints from PW3D dataset? The [README](https://docs.google.com/document/d/16rgJJGFLpR2V8nuSZFtcsMLWI341A41FsQ9Xix4j8IA/edit) you provided does not contain information about camera extrinsics and/or the world coordinates. Could you please release the code for converting PW3D to Json annotations (based on the official PW3D sequenceFiles/*.pkl)? Thanks.

**Comment by mks0601** [comment]
Oh I thought the extrinsics in 3DPW are not important because it is a single view dataset, so I did not included them in the `json` file.
I uploaded the converting code (3DPW -> COCO) in [here](https://github.com/mks0601/I2L-MeshNet_RELEASE/blob/master/tool/3dpw2coco.py).

**Comment by andgitchang** [comment]
I agree in most scenarios one can directly use the 24 camera joints provided by DW3D. However as for my use-case I'd like to extract some keypoints other than that of the 24 body joints. Thanks for your code, it saves my day.
