### ISSUE TITLE
where is gamma prediction from network?

### ISSUE THREAD

**Issue by wangzheallen** [mks0601/3DMPPE_ROOTNET_RELEASE#3]
https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE/blob/master/main/model.py
Could you please tell me where is the correction factor (gamma) prediction as mentioned in the original paper?

Thanks!

**Comment by mks0601** [comment]
`depth` in 70th line is estimated gamma.

**Comment by mks0601** [comment]
I changed variable names in a more clear way. Thanks!
