### ISSUE TITLE
pretrained file for demo.py is damaged

### ISSUE THREAD

**Issue by kdh4672** [mks0601/3DMPPE_ROOTNET_RELEASE#30]
I can't extract snapshot_18.pth.tar from your Google drive

error like this:
tar: This does not look like a tar archive
tar: Skipping to next header
tar: A lone zero block at 7115
tar: Exiting with failure status due to previous errors

**Comment by mks0601** [comment]
That is not a zipped file. You can just use it without the decompression.

**Comment by kdh4672** [comment]
But the file extension is tar.. How can I just use it without decompression?
When I try to run the file, it says I should decompress...

**Comment by mks0601** [comment]
Put snapshot_18.pth.tar at output/model_dump and run python tset.py --gpu 0 --test_epoch 18

**Comment by kdh4672** [comment]
thank you!!  Now it works~
