### ISSUE TITLE
DetectNet으로 resnet 50 + FPN 사용하신 것 맞나요..?

### ISSUE THREAD

**Issue by danke1** [mks0601/3DMPPE_ROOTNET_RELEASE#35]
개인 데이터 셋으로 학습시키기 위해 mask r cnn으로 bbox를 얻고자 하는데요,
Mask r cnn 중 resnet-50 +FPN 모델 사용하신 것 맞나요?

**Comment by mks0601** [comment]
issue를 계속해서 열지 말아주세요. resnet-50+fpn사용한거 맞습니다.

**Comment by danke1** [comment]
그럼 DetectNet에 돌릴 때, 아래의 코드를 이용해서 ground truth의 min_x, max_x, min_y, max_y 로 bbox 따서 예측값으로 넣어주는 건가요?

![스크린샷, 2021-08-23 09-38-22](https://user-images.githubusercontent.com/79454653/130375662-df3cc053-a150-4535-bab1-6a979114eed7.jpg)

**Comment by mks0601** [comment]
질문은 최대한 상세하게 해주시길 바랍니다. 어떤것을 묻는지 모르겠습니다. 그리고 저에게 모든걸 물어보지 마시고 danke1님께서 여러가지 시도해보시고 정말 해결이 안될때만 물어보시길 바랍니다. mask rcnn은 detectron2의 readme를 보시면 코드를 실행하는 법이 모두 나와있습니다.
