### ISSUE TITLE
test on wild images

### ISSUE THREAD

**Issue by dldaisy** [mks0601/3DMPPE_ROOTNET_RELEASE#36]
Hi,
I want to get the root depth in ndc space from a wild image, but the image was captured by another camera with different intrinsics(the focal length is different from 1500 used in the code).
Can I run rootnet inference on the image? If I can, how can I get the correct depth in NDC space？
Thanks a lot!

**Comment by mks0601** [comment]
RootNet predicts root depths in the focal length-normalized space.
I set the normalized focal lengths as (1500,1500), so the predicted depth is in (1500,1500) focal length space.
If you know true focal length, you can convert the predicted depth to the correct focal length space.

**Comment by dldaisy** [comment]
Hi @mks0601 
Thanks for reply! 
Does it mean I don't need to retrain the model but only needs to modify the focal length in demo.py?

**Comment by mks0601** [comment]
Yes.

**Comment by dldaisy** [comment]
I see. Thanks a lot!

**Comment by nicolasugrinovic** [comment]
Hi @mks0601, 
Kudos for the great work. I see that during the **evaluation for MuPots** dataset, you read this **focal length** parameter from **MuPoTS-3D.json** file. I was wondering, how did you get **instrinsics** parameters? Did you calculate these values or they come from the dataset. I believe I could not find them in the dataset.
Thanks
