### ISSUE TITLE
PoseNet

### ISSUE THREAD

**Issue by surelyee** [mks0601/3DMPPE_ROOTNET_RELEASE#5]
hello, thanks for your good work. 
Can you make me know where is your posenet code and MPJPE in your paper iccv2019? 
I am looking for your reply. thanks.

**Comment by mks0601** [comment]
https://github.com/mks0601/3DMPPE_POSENET_RELEASE

You can run the code with provided pre-trained model to get MPJPE.

**Comment by surelyee** [comment]
@mks0601 thanks, i run the code of test.py and only get MRPE, why no MPJPE?
python test.py --gpu 0-1 --test_epoch 7 ; for h36m dataset

**Comment by mks0601** [comment]
I think you ran RootNet

**Comment by surelyee** [comment]
@mks0601  I am sorry, i can't find the .py file to test RootNet, and the RootNet is  used in model.py, but it's result only is coord. the coord meaning maybe is the root of a person , the coord is (x,y,z) and the shape is (1,3),    is not the 17*3 jonit of one person.
thanks.

**Comment by mks0601** [comment]
Could you make it clear? Do you want RootNet or PoseNet? The RootNet localizes human root in camera-centered coordinate system. The output is (x,y,z) of human root joint, which means shape is (1,3). The PoseNet localizes human joints in root-relative coordinate system. The output is (x,y,z) of human joints, which means shape is (J,3).

**Comment by mks0601** [comment]
For the RootNet, use this repo. For the PoseNet, use above link.

**Comment by surelyee** [comment]
@mks0601  thank you very much!! this is my wrong  for the name.........thanks for your patient answer.
thanks a lot.
