### ISSUE TITLE
The issue of inaccurate deep prediction

### ISSUE THREAD

**Issue by YHaooo-4508** [mks0601/3DMPPE_ROOTNET_RELEASE#54]
I trained for 20 epochs and verified the accuracy. I found that the prediction accuracy of xy is very high, but the prediction accuracy of z value is very poor. Is there a problem with my training or is it just this kind of accuracy. 

The accuracy situation is shown in the following figure
![image](https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE/assets/80744649/bd30f498-6d31-411a-90dd-f0cb5b7df568)

**Comment by mks0601** [comment]
<img width="512" alt="Screenshot 2023-07-26 at 11 03 03 PM" src="https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE/assets/13601723/b77a3b12-dec0-41a2-b177-3e0f350f8408">

As the table shows, that number is similar to the reported ones.
Basically, it is very ambiguous to exactly regress absolute depth from a single image, the reason of the high error.
But it is better than existing baseline

**Comment by YHaooo-4508** [comment]
> <img alt="Screenshot 2023-07-26 at 11 03 03 PM" width="512" src="https://user-images.githubusercontent.com/13601723/256412832-b77a3b12-dec0-41a2-b177-3e0f350f8408.png">
> As the table shows, that number is similar to the reported ones. Basically, it is very ambiguous to exactly regress absolute depth from a single image, the reason of the high error. But it is better than existing baseline

Thank you for your reply. Additionally, I would like to inquire if feature fusion with depth maps can solve this problem. 
Or, if there is a depth map, there is no need to infer the root point z value anymore？

**Comment by mks0601** [comment]
If you have depth maps, the problem becomes much easier, but still, you need to estimate it as depth map provides information of only visible surface. If your root joint is occluded by objects or some other parts of humans, such as arms, then you cannot directly retrieve depth values from the depth map.

**Comment by YHaooo-4508** [comment]
> If you have depth maps, the problem becomes much easier, but still, you need to estimate it as depth map provides information of only visible surface. If your root joint is occluded by objects or some other parts of humans, such as arms, then you cannot directly retrieve depth values from the depth map.

Thank you again. You have answered my question very well and I will close this issue
