### ISSUE TITLE
Models Corrupted

### ISSUE THREAD

**Issue by fraserprice** [mks0601/3DMPPE_ROOTNET_RELEASE#7]
I have attempted to download every pre-trained model linked (H36M Protocol 1+2 and MSCOCO) and both cannot be unzipped as files are corrupt: [1](https://i.gyazo.com/96b0034223b0891da17275f1bb320326.png), [2](https://i.gyazo.com/0e49aa0f62ffa3ac408c4dfd6f0afc8d.png).

I have tried multiple tools for unzipping, and outcome is the same- could you check that files have been correctly zipped?

Edit: This is the same for models in PoseNet repo.

**Comment by mks0601** [comment]
Oh `pth.tar` is not zipped one. You can directly use that as a pre-trained model.

**Comment by fraserprice** [comment]
> Oh `pth.tar` is not zipped one. You can directly use that as a pre-trained model.

Ah my bad...
