### ISSUE TITLE
`mem_info` not defined

### ISSUE THREAD

**Issue by fraserprice** [mks0601/3DMPPE_ROOTNET_RELEASE#8]
The `mem_info()` function (used in `test.py` and `train.py`) is not defined.

**Comment by mks0601** [comment]
I didn't noticed that because I always input gpu numbers correctly. Could you check your gpu numbers when running code?

**Comment by fraserprice** [comment]
> I didn't noticed that because I always input gpu numbers correctly. Could you check your gpu numbers when running code?

It's no worries for me as yeah I can manually input GPU indices, but it does throw an error whenever GPU isn't manually inputted as `mem_info()` doesn't seem to exist anywhere. Might just want to remove or have a look at what it is meant to achieve. It's also used in PoseNet code and isn't defined there either. Just wanted to make sure you're aware of it.

Thanks once more for quick replies, sorry for constant bombardment with issues as I know you're busy!
