### ISSUE TITLE
Question about COCO dataset

### ISSUE THREAD

**Issue by sdxass** [mks0601/3DMPPE_ROOTNET_RELEASE#9]
Hi, first of all, thank you for open sourcing such a great repo.

I would like to ask how did you train MSCOCO together with MuCO dataset? They have 
different joints configuration.

**Comment by sdxass** [comment]
DId you train MSCOCO together with MuCO dataset for multi-person pose estimation?

**Comment by mks0601** [comment]
Hi,
Each mini-batch consists of half-COCO and half-MuCO items. More details are described in Section 8.2 of the paper (https://arxiv.org/pdf/1907.11346.pdf)

**Comment by sdxass** [comment]
Understood. Thank you for your reply!
